## 15. item9 try-finally 보다 try-with-resources를 사용하라

- try-finally 는 더이상 최선의 방법이 아니다. (자바7부터)
- try-with-resources를 사용하면 코드가 더 짧고 분명하다.
- 만들어지는 예외 정보도 훨씬 유용하다.

````java
BufferedReader br = new BufferedReader(new FileReader(path));
try {
  return br.readLine();
} finally {
  br.close();
}
````

위 코드 처럼 finally 를 사용하여 자원을 회수해도 문제는 없다. 
좀 더 복잡한 코드를 보자.
````java
InputStream in = new FileInputStream(fileName);
try {
  OutputStream out = new FileOutputStream(dst);
  try {
    byte[] buf = new byte[8 * 1024];
    int n;
    while ((n = in.read(buf)) >= 0) {
      out.write(buf, 0, n);
    } finally {
      out.close();
    }
  }
} finally {
  in.close();
}
````

복잡해 졌다. 물론 try 안의 try 있는 구문을 하나로 하면 괜찮은거 아닌가 라는 의문을 가질 수 있다.
````java
InputStream in = new FileInputStream(fileName);
OutputStream out = new FileOutputStream(dst);
try {
  byte[] buf = new byte[8 * 1024];
  int n;
  while ((n = in.read(buf)) >= 0) {
      out.write(buf, 0, n);
  }
} finally {
  out.close();
  in.close();
}
````

위 코드처럼 할 수 있다.
하지만 메모리릭이 발생할 수 있는 코드이다.
만약 out.close() 이 부분에서 에러가 발생한다면 out.close() 코드가 실행도 안되고, in.close() 여기 코드도 실행이 안된 상태로 계속 유지될 것이다.

try-with-resources 를 사용하여 더 이상 위 문제들을 겪지 않아도 된다.
````java
try (BufferedReader br = new BufferedReader(new FileReader(path))) {
  return br.readLine();
}
````

우리가 더 이상 finally 에서 close()를 실행 안 해도 된다.
왜냐하면 try-with-resources 에서 사용할 수 있는 클래스들을 Closeable 인터페이스를 상속 받고 
그리고 Closeable는 AutoCloseable 를 상속한다.
따라서 따로 finally 에서 close() 메소드를 실행하지 않아도 된다.

다음으로 위 복잡한 코드를 바꿔보겠다.
````java
try (InputStream in = new FileInputStream(fileName); OutputStream out = new FileOutputStream(dst)) {
  byte[] buf = new byte[8 * 1024];
  int n;
  while ((n = in.read(buf)) >= 0) {
      out.write(buf, 0, n);
  }
}
````

이제 진짜 중요한 문제를 보자
진짜 문제는 예외에서 발생한다.
만약 try에서 예외가 발생하고, finally에서도 예외가 발생한다면 우리에게 보여지는 에러는 finally에서 발생한 에러이다.
여기서 문제가 나타난다.
우리는 처음 발생한 예외를 찾아 수정해야 하니만 finally 에서 발생한 예외를 보여주기 때문에 우리는 알수가 없다.

````java
readLine <- exception1 예외 발생
close() <- exception2 예외 발생

BufferedReader br = new BufferedReader(new FileReader(path));
try {
  return br.readLine();
} finally {
  br.close();
}

결과
exception2 예외 로그만 출력
````

하지만 try-with-resources 는 exception1 과 exception2 모두 출력해준다.

````java
readLine <- exception1 예외 발생
close() <- exception2 예외 발생

try (BufferedReader br = new BufferedReader(new FileReader(path))) {
  return br.readLine();
}

결과
exception1, exception2 순서대로 예외 로그 출력
````
